spring.application.name=ExpenseTracker
server.port=8080
jwt.secretKey=kubytvi76btyvu56fjfh5jhkfctlkwaushorinuhsveiurbhseiurbvhsoybfyhrybretybtfytdf
spring.datasource.url=jdbc:postgresql://localhost:5432/expensedb
spring.datasource.username=harshraj
spring.datasource.password=Harsh@3417
spring.data.web.pageable.serialization-mode=via-dto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#redis config
#spring.cache.type=none
#spring.data.redis.host=redis-11606.c212.ap-south-1-1.ec2.cloud.redislabs.com
#spring.data.redis.port=11606
#spring.data.redis.password=Z9fzXZNgAmbihUAjxf8rS8nDF04GcQj1