spring.application.name=ExpenseTracker
server.port=8080
jwt.secretKey=kubytvi76btyvu56fjfh5jhkfctlkwaushorinuhsveiurbhseiurbvhsoybfyhrybretybtfytdf
spring.datasource.url=jdbc:postgresql://localhost:5432/expensedb
spring.datasource.username=
spring.datasource.password=
spring.data.web.pageable.serialization-mode=via-dto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
redis config
spring.cache.type=redis
spring.data.redis.host={USE_YOUR_OWN}
spring.data.redis.port=11606
spring.data.redis.password={USE_YOUR_OWN}
